version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/build"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/.config"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/Prefab/templates/prefab"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/Prefab/templates/prefab/build"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/Prefab/templates/prefab/.config"
    schedule:
      interval: "weekly"
