language: csharp

os:
  - osx
  - linux

dist: trusty
dotnet: 2.1.300

branches:
  only:
    - master

before_script:
  - chmod +x ./build.sh

script:
  - ./build.sh
  
notifications: 
  email: false
