image: Visual Studio 2017

environment:
  GITHUB_API_KEY:
    secure: LJrSXwtcUSbB8eOrrzwpkfoXP4I/19wJWEz/Zo+++/jrzj1MkmDpzXkhu0gs0S6r

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: artifacts\*.nupkg

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
