name: publish

on:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/*.nupkg
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["artifacts/*.nupkg"]'